"""
urdu_translator.py — Gemini-powered English → Urdu translation layer.

This module sits AFTER the Groq/LLaMA RAG answer is generated. It takes the
already-generated English answer (from llm_chains.py) and asks Google Gemini
to render it into natural, grammatically correct Urdu — preserving tone,
register, and any structure (headings, lists, quoted lines, page references)
from the original.

Design notes:
  - Kept as a separate module (not merged into llm_chains.py) because it is a
    distinct concern: translation/localisation, not RAG answer generation.
  - Uses the `google-generativeai` SDK. Model defaults to "gemini-1.5-flash"
    (fast + cheap, good enough for translation; swap to "gemini-1.5-pro" in
    get_gemini_model() below if you want higher translation quality).
  - Mirrors the graceful-error-handling pattern already used for Groq in
    llm_chains.py, so failures show up as friendly messages in the UI instead
    of raw stack traces.
"""

from typing import Optional

import google.generativeai as genai
from google.api_core import exceptions as google_exceptions


# ── Model factory ─────────────────────────────────────────────────────────────

def get_gemini_model(api_key: str, model_name: str = "gemini-2.5-flash"):
    """
    Configure the Gemini SDK with the given API key and return a model handle.
    Call this once (e.g. cached in Streamlit session_state) and reuse it.
    """
    genai.configure(api_key=api_key)
    return genai.GenerativeModel(model_name)


# ── Translation prompt ────────────────────────────────────────────────────────

URDU_TRANSLATION_SYSTEM_PROMPT = """You are an expert Urdu translator and language editor, translating
educational content for a Grade 3 English-textbook tutoring app.

You will be given an English answer that was generated by an AI tutor. Translate it into natural,
fluent Urdu while following these rules exactly:

1. GRAMMAR: Use correct, standard Urdu grammar (سنسکرت/فارسی مبنی درست قواعد) — correct verb
   conjugation, gender agreement (مذکر/مؤنث), correct izafat construction, and correct word order
   (Urdu is SOV, not SVO like English). Do not produce a word-for-word transliteration.

2. TONE: Preserve the original tone. If the English text is encouraging/friendly (as with a
   Grade 3 teacher), the Urdu must sound equally warm and encouraging, not stiff or overly formal.
   Use the respectful "آپ" form, appropriate for a teacher addressing a young student.

3. STRUCTURE: Preserve the structure of the original — keep Markdown headings (##), bullet
   points, numbered lists, and bold/italic emphasis. Keep table structure if present.

4. PROPER NOUNS & QUOTES: Keep proper nouns (character names, book/unit titles, place names)
   in their original Roman spelling if translating them would be awkward or lose meaning
   (e.g. keep "Shahid", "The Drawn Match" as-is, optionally followed by an Urdu gloss in brackets).
   Keep page/unit references (e.g. "Page 6", "Unit 3") in the same numeric format.

5. VOCABULARY WORDS: If the English text is specifically teaching an English vocabulary word or
   grammar rule (e.g. explaining "run" vs "ran"), KEEP the English word/example intact and add
   the Urdu explanation around it — do not translate the English example itself into Urdu.

6. ENCODING: Output must be in proper Urdu script (Nastaliq-compatible Unicode), never in Roman
   Urdu.

7. DO NOT add any commentary, disclaimers, or notes about the translation itself. Output ONLY
   the translated Urdu text, ready to be shown directly to the student/teacher.

Now translate the following text:
"""


# ── Core translation function ─────────────────────────────────────────────────

def translate_to_urdu(gemini_model, english_text: str) -> str:
    """
    Translate an English answer/exam-paper/answer-key string into Urdu using Gemini.
    Returns a friendly, prefixed error message string on failure (never raises),
    matching the error-handling style already used for Groq calls in llm_chains.py.
    """
    if not english_text or not english_text.strip():
        return ""

    prompt = f"{URDU_TRANSLATION_SYSTEM_PROMPT}\n\n---\n{english_text}\n---"

    try:
        response = gemini_model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.3,   # low temperature: faithful translation, not creative rewriting
                max_output_tokens=4096,
            ),
        )
        return (response.text or "").strip()

    except google_exceptions.Unauthenticated:
        return ("❌ **Invalid Gemini API key.** Please check the key you entered in the sidebar "
                "(get one free at aistudio.google.com/apikey).")
    except google_exceptions.PermissionDenied:
        return ("❌ **Gemini API key rejected (permission denied).** Make sure the Generative "
                "Language API is enabled for this key's project.")
    except google_exceptions.ResourceExhausted:
        return ("⏳ **Gemini rate limit reached.** You've hit the free-tier quota. "
                "Wait a minute and try again.")
    except google_exceptions.GoogleAPICallError as e:
        return f"🔴 **Gemini API error:** {e}"
    except Exception as e:  # noqa: BLE001 — final safety net so the UI never crashes
        return f"🔴 **Urdu translation failed:** {e}"


def is_urdu_translation_available(gemini_api_key: Optional[str]) -> bool:
    """Simple guard used by app.py before attempting a translation call."""
    return bool(gemini_api_key and gemini_api_key.strip())
